# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c44e0cf7b4ae93878bc11667ceef54ad"
name = "p-options"
application_url = "https://mpg-acne-records-gourmet.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "debug4221.myshopify.com"

[auth]
redirect_urls = [
  "https://mpg-acne-records-gourmet.trycloudflare.com/auth/callback",
  "https://mpg-acne-records-gourmet.trycloudflare.com/auth/shopify/callback",
  "https://mpg-acne-records-gourmet.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
