# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "0567304c584526e79aa3250b58dbd2bc"
name = "test8888"
application_url = "https://certain-nicaragua-suspension-oval.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "debug-mm.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_content,read_metaobjects,read_product_listings,read_products,write_content,write_metaobject_definitions,write_metaobjects,write_product_listings,write_products"

[auth]
redirect_urls = [
  "https://certain-nicaragua-suspension-oval.trycloudflare.com/auth/callback",
  "https://certain-nicaragua-suspension-oval.trycloudflare.com/auth/shopify/callback",
  "https://certain-nicaragua-suspension-oval.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2025-01"

[pos]
embedded = false
