# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "cfe659d7b69e53be256d5f7d162dbb72"
name = "php-app"
application_url = "https://intl-trips-hong-events.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "debug4221.myshopify.com"

[auth]
redirect_urls = [
  "https://intl-trips-hong-events.trycloudflare.com/auth/callback",
  "https://intl-trips-hong-events.trycloudflare.com/auth/shopify/callback",
  "https://intl-trips-hong-events.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
