# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d1485832ef627a85832eabba069d261a"
name = "page-builder"
handle = "page-builder-2"
application_url = "https://89ae-61-141-73-243.ngrok-free.app"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "debug4221.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://89ae-61-141-73-243.ngrok-free.app/auth/callback",
  "https://89ae-61-141-73-243.ngrok-free.app/auth/shopify/callback",
  "https://89ae-61-141-73-243.ngrok-free.app/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
