# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "product-qrcode"
client_id = "517e6641383bd263cbe3e907fdcbc0e2"
application_url = "https://donors-payments-periods-loops.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://donors-payments-periods-loops.trycloudflare.com/auth/callback",
  "https://donors-payments-periods-loops.trycloudflare.com/auth/shopify/callback",
  "https://donors-payments-periods-loops.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "myapptest1523.myshopify.com"
