# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "90347ccfce92f8080d47f3aae0268986"
application_url = "https://honestly-endless-ghoul.ngrok-free.app"
embedded = true
name = "test123"
handle = "test123-305"

[build]
automatically_update_urls_on_dev = true
dev_store_url = "debug-mm.myshopify.com"
include_config_on_deploy = true

[webhooks]
api_version = "2025-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_content,write_content,read_products"

[auth]
redirect_urls = [
  "https://honestly-endless-ghoul.ngrok-free.app/auth/callback",
  "https://honestly-endless-ghoul.ngrok-free.app/auth/shopify/callback",
  "https://honestly-endless-ghoul.ngrok-free.app/api/auth/callback"
]

[pos]
embedded = false
