# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "96517be1441f4755a855bc64b3a8df67"
application_url = "https://privilege-sponsor-fiscal-ab.trycloudflare.com"
embedded = true
name = "pp-options"
handle = "pp-options-1"

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://privilege-sponsor-fiscal-ab.trycloudflare.com/auth/callback",
  "https://privilege-sponsor-fiscal-ab.trycloudflare.com/auth/shopify/callback",
  "https://privilege-sponsor-fiscal-ab.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "debug4221.myshopify.com"
automatically_update_urls_on_dev = true
