# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "90347ccfce92f8080d47f3aae0268986"
application_url = "https://being-artificial-accident-trick.trycloudflare.com"
embedded = true
name = "test123"
handle = "test123-305"

[build]
automatically_update_urls_on_dev = true
dev_store_url = "debug-mm.myshopify.com"
include_config_on_deploy = true

[webhooks]
api_version = "2025-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://being-artificial-accident-trick.trycloudflare.com/auth/callback",
  "https://being-artificial-accident-trick.trycloudflare.com/auth/shopify/callback",
  "https://being-artificial-accident-trick.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
