# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "cfe659d7b69e53be256d5f7d162dbb72"
name = "php-app"
handle = "php-app-171"
application_url = "https://longitude-assistance-counties-leu.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "debug4221.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://longitude-assistance-counties-leu.trycloudflare.com/auth/callback",
  "https://longitude-assistance-counties-leu.trycloudflare.com/auth/shopify/callback",
  "https://longitude-assistance-counties-leu.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false


# custom app acctoken: shp六六六at_f99215f4c13d2e481642bc527e90ae13六六六六
